# Generated by Django 3.2.7 on 2022-05-26 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='ตัวเลือก')),
                ('answer', models.CharField(blank=True, max_length=255, null=True, verbose_name='คำตอบ')),
                ('correct', models.BooleanField(blank=True, default=False, null=True, verbose_name='ถูก/ผิด')),
            ],
            options={
                'verbose_name_plural': 'คำตอบ',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineId', models.CharField(max_length=255, verbose_name='Line ID')),
                ('fullname', models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อ-นามสกุล')),
                ('rank', models.CharField(blank=True, max_length=255, null=True, verbose_name='ยศ')),
                ('unit', models.CharField(blank=True, max_length=255, null=True, verbose_name='สังกัด')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='อีเมล์')),
                ('mobile', models.CharField(blank=True, max_length=10, null=True, verbose_name='เบอร์มือถือ')),
                ('officePhone', models.CharField(blank=True, max_length=10, null=True, verbose_name='เบอร์ที่ทำงาน')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='ตำแหน่ง')),
                ('state', models.IntegerField(choices=[(0, 'ยังไม่ได้ลงทะเบียน'), (1, 'เสร็จสิ้น')], default=0, verbose_name='สถานะ')),
                ('last_response', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'ผู้ลงทะเบียน',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='ข้อที่')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='โจทย์')),
                ('img', models.ImageField(upload_to='uploads/', verbose_name='รูปภาพ')),
                ('is_current', models.BooleanField(default=False, verbose_name='คำถามปัจจุบัน')),
            ],
            options={
                'verbose_name_plural': 'คำถาม',
            },
        ),
        migrations.CreateModel(
            name='PlayerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='คะแนน')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='เวลาที่บันทึก')),
                ('choice_selected', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='คำตอบ', to='User.choice')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ผู้ลงทะเบียน', to='User.player')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='คำถาม', to='User.question')),
            ],
            options={
                'verbose_name_plural': 'ผู้ตอบแบบสอบถาม',
            },
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_ATK_FK', to='User.question'),
        ),
    ]
