# Generated by Django 3.2.7 on 2022-05-26 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='lineId',
            new_name='line_id',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='officePhone',
            new_name='office_phone',
        ),
    ]
