# Generated by Django 3.2.7 on 2022-05-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20220526_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='img',
            field=models.CharField(default='-', max_length=255, verbose_name='รูปภาพ'),
        ),
    ]
