# Generated by Django 3.2.7 on 2022-05-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_player_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='state',
            field=models.IntegerField(choices=[(0, 'ยังไม่ได้ลงทะเบียน'), (1, 'อัพเดทข้อมูล ทอ.'), (2, 'อัพเดทจาก Line'), (3, 'ลงทะเบียนสมบูรณ์')], default=0, verbose_name='สถานะ'),
        ),
    ]
