# Generated by Django 3.2.7 on 2022-06-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_player_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ready',
            field=models.BooleanField(default=False, verbose_name='พร้อม'),
        ),
        migrations.AddField(
            model_name='question',
            name='send_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='เวลาส่งคำถาม'),
        ),
    ]
