# Generated by Django 3.2.7 on 2022-06-07 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_raking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Raking',
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer', to='User.player'),
        ),
    ]
