# Generated by Django 3.2.7 on 2022-06-07 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_auto_20220607_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raking',
            fields=[
            ],
            options={
                'verbose_name': 'คำนวนคะแนน',
                'verbose_name_plural': 'คำนวนคะแนน',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('User.playerdata',),
        ),
    ]
