# Generated by Django 3.2.7 on 2022-06-09 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_auto_20220609_0826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='total_time',
            new_name='time',
        ),
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='คะแนนรวม'),
        ),
    ]
