# Generated by Django 3.2.7 on 2023-05-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_auto_20230529_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='config name')),
                ('line_channel_access_token', models.TextField()),
                ('line_user_id', models.TextField()),
                ('line_liff_id', models.TextField()),
                ('line_url', models.TextField()),
                ('url_website', models.TextField()),
                ('is_rtaf_authen', models.BooleanField(default=False, verbose_name='rtaf auth')),
            ],
        ),
    ]
