# Generated by Django 3.2.7 on 2023-05-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='อายุ'),
        ),
        migrations.AddField(
            model_name='player',
            name='provide',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='โรงเรียน'),
        ),
    ]
