# Generated by Django 3.2.7 on 2023-05-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_auto_20230529_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='address',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='ที่อยู่'),
        ),
    ]
